---

- name: Apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

- name: Deploy MySQL and configure the databases
  hosts: dbservers
  user: root

  roles:
    - mariadb

- name: Configure and deploy the webservers and application code
  hosts: webservers
  user: root

  roles:
    - nginx
    - php-fpm
    - composer
    - nodejs
    - elasticsearch
    - mri
    - { role: users, when: developers is defined }
